name: Run static analysis

on:
  workflow_dispatch:
  push:
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./src

    steps:
    - uses: actions/checkout@v3

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-
    - name: Install dependencies
      run: composer install --prefer-dist --no-progress
      
    - name: Run phpmd
      run: |
        ./vendor/bin/phpmd ./PHPBasics/Processor/,./PHPBasics/index.php github phpmd.ruleset.xml
        ./vendor/bin/phpmd ./php-advanced/src,./php-advanced/templates/  github phpmd.ruleset.xml
    
    - name: Run phpstan
      run: vendor/bin/phpstan analyse ./PHPBasics/Processor/ ./PHPBasics/index.php --level 6
